# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pengzhixiang/test/myserver/server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pengzhixiang/test/myserver/server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pengzhixiang/test/myserver/server/CMakeFiles /home/pengzhixiang/test/myserver/server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pengzhixiang/test/myserver/server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named buffer

# Build rule for target.
buffer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 buffer
.PHONY : buffer

# fast build rule for target.
buffer/fast:
	$(MAKE) -f buffer/CMakeFiles/buffer.dir/build.make buffer/CMakeFiles/buffer.dir/build
.PHONY : buffer/fast

#=============================================================================
# Target rules for targets named mysqlc

# Build rule for target.
mysqlc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysqlc
.PHONY : mysqlc

# fast build rule for target.
mysqlc/fast:
	$(MAKE) -f mysql/CMakeFiles/mysqlc.dir/build.make mysql/CMakeFiles/mysqlc.dir/build
.PHONY : mysqlc/fast

#=============================================================================
# Target rules for targets named protocol

# Build rule for target.
protocol: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 protocol
.PHONY : protocol

# fast build rule for target.
protocol/fast:
	$(MAKE) -f protocol/CMakeFiles/protocol.dir/build.make protocol/CMakeFiles/protocol.dir/build
.PHONY : protocol/fast

#=============================================================================
# Target rules for targets named daemon

# Build rule for target.
daemon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 daemon
.PHONY : daemon

# fast build rule for target.
daemon/fast:
	$(MAKE) -f daemon/CMakeFiles/daemon.dir/build.make daemon/CMakeFiles/daemon.dir/build
.PHONY : daemon/fast

#=============================================================================
# Target rules for targets named log

# Build rule for target.
log: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 log
.PHONY : log

# fast build rule for target.
log/fast:
	$(MAKE) -f log/CMakeFiles/log.dir/build.make log/CMakeFiles/log.dir/build
.PHONY : log/fast

#=============================================================================
# Target rules for targets named timer

# Build rule for target.
timer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 timer
.PHONY : timer

# fast build rule for target.
timer/fast:
	$(MAKE) -f timer/CMakeFiles/timer.dir/build.make timer/CMakeFiles/timer.dir/build
.PHONY : timer/fast

#=============================================================================
# Target rules for targets named IMserver

# Build rule for target.
IMserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IMserver
.PHONY : IMserver

# fast build rule for target.
IMserver/fast:
	$(MAKE) -f server/CMakeFiles/IMserver.dir/build.make server/CMakeFiles/IMserver.dir/build
.PHONY : IMserver/fast

#=============================================================================
# Target rules for targets named IMclient

# Build rule for target.
IMclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IMclient
.PHONY : IMclient

# fast build rule for target.
IMclient/fast:
	$(MAKE) -f client/CMakeFiles/IMclient.dir/build.make client/CMakeFiles/IMclient.dir/build
.PHONY : IMclient/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... buffer"
	@echo "... mysqlc"
	@echo "... protocol"
	@echo "... daemon"
	@echo "... log"
	@echo "... timer"
	@echo "... IMserver"
	@echo "... IMclient"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

