// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: regserverres.proto

#ifndef PROTOBUF_regserverres_2eproto__INCLUDED
#define PROTOBUF_regserverres_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_regserverres_2eproto();
void protobuf_AssignDesc_regserverres_2eproto();
void protobuf_ShutdownFile_regserverres_2eproto();

class RegServerRes;

// ===================================================================

class RegServerRes : public ::google::protobuf::Message {
 public:
  RegServerRes();
  virtual ~RegServerRes();

  RegServerRes(const RegServerRes& from);

  inline RegServerRes& operator=(const RegServerRes& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RegServerRes& default_instance();

  void Swap(RegServerRes* other);

  // implements Message ----------------------------------------------

  RegServerRes* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RegServerRes& from);
  void MergeFrom(const RegServerRes& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 serverid = 1;
  inline bool has_serverid() const;
  inline void clear_serverid();
  static const int kServeridFieldNumber = 1;
  inline ::google::protobuf::uint32 serverid() const;
  inline void set_serverid(::google::protobuf::uint32 value);

  // required uint32 port = 2;
  inline bool has_port() const;
  inline void clear_port();
  static const int kPortFieldNumber = 2;
  inline ::google::protobuf::uint32 port() const;
  inline void set_port(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:RegServerRes)
 private:
  inline void set_has_serverid();
  inline void clear_has_serverid();
  inline void set_has_port();
  inline void clear_has_port();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 serverid_;
  ::google::protobuf::uint32 port_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_regserverres_2eproto();
  friend void protobuf_AssignDesc_regserverres_2eproto();
  friend void protobuf_ShutdownFile_regserverres_2eproto();

  void InitAsDefaultInstance();
  static RegServerRes* default_instance_;
};
// ===================================================================


// ===================================================================

// RegServerRes

// required uint32 serverid = 1;
inline bool RegServerRes::has_serverid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RegServerRes::set_has_serverid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RegServerRes::clear_has_serverid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RegServerRes::clear_serverid() {
  serverid_ = 0u;
  clear_has_serverid();
}
inline ::google::protobuf::uint32 RegServerRes::serverid() const {
  return serverid_;
}
inline void RegServerRes::set_serverid(::google::protobuf::uint32 value) {
  set_has_serverid();
  serverid_ = value;
}

// required uint32 port = 2;
inline bool RegServerRes::has_port() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RegServerRes::set_has_port() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RegServerRes::clear_has_port() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RegServerRes::clear_port() {
  port_ = 0u;
  clear_has_port();
}
inline ::google::protobuf::uint32 RegServerRes::port() const {
  return port_;
}
inline void RegServerRes::set_port(::google::protobuf::uint32 value) {
  set_has_port();
  port_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_regserverres_2eproto__INCLUDED
